### ISSUE TITLE
util-linux: private method `xz_dep'

### ISSUE THREAD

**Issue by konstin** [Linuxbrew/brew#185]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

### Bug reports:

linux-util is required for postgis, so I can neither install postgis nor linux-util:

```
$ brew install util-linux
==> Downloading https://www.kernel.org/pub/linux/utils/util-linux/v2.29/util-linux-2.29.tar.xz
Already downloaded: /home/utasart/.cache/Homebrew/util-linux-2.29.tar.xz
Error: private method `xz_dep' called for #<DependencyCollector:0x007f9b9349d398>
Please report this bug:
  https://github.com/Linuxbrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting
/home/utasart/.linuxbrew/Library/Homebrew/dependency_collector.rb:65:in `tar_needs_xz_dependency?'
/home/utasart/.linuxbrew/Library/Homebrew/download_strategy.rb:244:in `block in stage'
/home/utasart/.linuxbrew/Library/Homebrew/utils.rb:255:in `with_system_path'
/home/utasart/.linuxbrew/Library/Homebrew/download_strategy.rb:243:in `stage'
/home/utasart/.linuxbrew/Library/Homebrew/resource.rb:95:in `block in unpack'
/home/utasart/.linuxbrew/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/home/utasart/.linuxbrew/Library/Homebrew/extend/fileutils.rb:74:in `block in run'
/home/utasart/.linuxbrew/Library/Homebrew/extend/fileutils.rb:74:in `chdir'
/home/utasart/.linuxbrew/Library/Homebrew/extend/fileutils.rb:74:in `run'
/home/utasart/.linuxbrew/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/home/utasart/.linuxbrew/Library/Homebrew/resource.rb:94:in `unpack'
/home/utasart/.linuxbrew/Library/Homebrew/resource.rb:86:in `stage'
/home/utasart/.linuxbrew/Library/Homebrew/formula.rb:1799:in `stage'
/home/utasart/.linuxbrew/Library/Homebrew/formula.rb:1075:in `brew'
/home/utasart/.linuxbrew/Library/Homebrew/build.rb:112:in `install'
/home/utasart/.linuxbrew/Library/Homebrew/build.rb:189:in `<main>'
```

## `brew doctor` output
```
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Setting LD_* vars can break dynamic linking.
Set variables:
  LD_LIBRARY_PATH: /home/utasart/.toast/armed/lib:/package/host/localhost/postgresql-9.2/lib/:

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /package/host/localhost/python-3.5/bin/python3-config
  /package/host/localhost/python-3.5/bin/python3.5m-config
  /package/host/localhost/python-3.5/bin/python3.5-config
  /package/host/localhost/php-7.0/bin/php-config
  /usr/local/bin/python3-config
  /usr/local/bin/python3.2-config
  /usr/local/bin/python3.3m-config
  /usr/local/bin/python2.7-config
  /usr/local/bin/python3.2m-config
  /usr/local/bin/python3.4-config
  /usr/local/bin/python3.3-config
  /usr/local/bin/python3.4m-config
  /usr/local/sbin/uberspace-update-spamassassin-config
  /usr/local/sbin/uberspace-generate-nginx-acme-config
```

**Comment by bw-yuhogg** [comment]
Thanks for reporting @konstin!

Can you do another `brew update` and try again please? I believe I fixed this issue earlier this morning (https://github.com/Linuxbrew/brew/pull/183).

**Comment by konstin** [comment]
In this case the update hasn't reached me:

```
$ brew update
Already up-to-date.
```

**Comment by bw-yuhogg** [comment]
EDIT: my apologies; I forgot that #183 hasn't gotten into a stable release yet. I'll try to make one as soon as possible.

**Comment by konstin** [comment]
Thanks for responding so fast! I'll wait for the update and then re-check this issue.

**Comment by axiac** [comment]
I got the same error (and the same stack trace) while trying to install `gettext` (as a dependency of `php56`) on a fresh Linuxbrew install.

`brew doctor` doesn't report anything abnormal (`Your system is ready to brew.`), `brew update` says `Already up-to-date.`.

**Comment by konstin** [comment]
After manually pulling latest master (yes, I'm aware that not the recommended way of updating), I get the following error:

```
$ brew install util-linux
==> Downloading https://www.kernel.org/pub/linux/utils/util-linux/v2.29/util-linux-2.29.tar.xz
Already downloaded: /home/utasart/.cache/Homebrew/util-linux-2.29.tar.xz
==> ./configure --disable-silent-rules --prefix=/home/utasart/.linuxbrew/Cellar/util-linux/2.29 --disable-use-tty-group --disable-kill --disable-cal --disable-ul
==> make install
Last 15 lines from /home/utasart/.cache/Homebrew/Logs/util-linux/02.make:
libtool: link: /home/utasart/.linuxbrew/bin/gcc-5 -shared  -fPIC -DPIC  libblkid/src/.libs/libblkid_la-init.o libblkid/src/.libs/libblkid_la-cache.o libblkid/src/.libs/libblkid_la-config.o libblkid/src/.libs/libblkid_la-dev.o libblkid/src/.libs/libblkid_la-devname.o libblkid/src/.libs/libblkid_la-devno.o libblkid/src/.libs/libblkid_la-encode.o libblkid/src/.libs/libblkid_la-evaluate.o libblkid/src/.libs/libblkid_la-getsize.o libblkid/src/.libs/libblkid_la-llseek.o libblkid/src/.libs/libblkid_la-probe.o libblkid/src/.libs/libblkid_la-read.o libblkid/src/.libs/libblkid_la-resolve.o libblkid/src/.libs/libblkid_la-save.o libblkid/src/.libs/libblkid_la-tag.o libblkid/src/.libs/libblkid_la-verify.o libblkid/src/.libs/libblkid_la-version.o libblkid/src/partitions/.libs/libblkid_la-aix.o libblkid/src/partitions/.libs/libblkid_la-bsd.o libblkid/src/partitions/.libs/libblkid_la-dos.o libblkid/src/partitions/.libs/libblkid_la-gpt.o libblkid/src/partitions/.libs/libblkid_la-mac.o libblkid/src/partitions/.libs/libblkid_la-minix.o libblkid/src/partitions/.libs/libblkid_la-partitions.o libblkid/src/partitions/.libs/libblkid_la-sgi.o libblkid/src/partitions/.libs/libblkid_la-solaris_x86.o libblkid/src/partitions/.libs/libblkid_la-sun.o libblkid/src/partitions/.libs/libblkid_la-ultrix.o libblkid/src/partitions/.libs/libblkid_la-unixware.o libblkid/src/superblocks/.libs/libblkid_la-adaptec_raid.o libblkid/src/superblocks/.libs/libblkid_la-bcache.o libblkid/src/superblocks/.libs/libblkid_la-befs.o libblkid/src/superblocks/.libs/libblkid_la-bfs.o libblkid/src/superblocks/.libs/libblkid_la-btrfs.o libblkid/src/superblocks/.libs/libblkid_la-cramfs.o libblkid/src/superblocks/.libs/libblkid_la-ddf_raid.o libblkid/src/superblocks/.libs/libblkid_la-drbd.o libblkid/src/superblocks/.libs/libblkid_la-drbdproxy_datalog.o libblkid/src/superblocks/.libs/libblkid_la-drbdmanage.o libblkid/src/superblocks/.libs/libblkid_la-exfat.o libblkid/src/superblocks/.libs/libblkid_la-ext.o libblkid/src/superblocks/.libs/libblkid_la-f2fs.o libblkid/src/superblocks/.libs/libblkid_la-gfs.o libblkid/src/superblocks/.libs/libblkid_la-hfs.o libblkid/src/superblocks/.libs/libblkid_la-highpoint_raid.o libblkid/src/superblocks/.libs/libblkid_la-hpfs.o libblkid/src/superblocks/.libs/libblkid_la-iso9660.o libblkid/src/superblocks/.libs/libblkid_la-isw_raid.o libblkid/src/superblocks/.libs/libblkid_la-jfs.o libblkid/src/superblocks/.libs/libblkid_la-jmicron_raid.o libblkid/src/superblocks/.libs/libblkid_la-linux_raid.o libblkid/src/superblocks/.libs/libblkid_la-lsi_raid.o libblkid/src/superblocks/.libs/libblkid_la-luks.o libblkid/src/superblocks/.libs/libblkid_la-lvm.o libblkid/src/superblocks/.libs/libblkid_la-minix.o libblkid/src/superblocks/.libs/libblkid_la-netware.o libblkid/src/superblocks/.libs/libblkid_la-nilfs.o libblkid/src/superblocks/.libs/libblkid_la-ntfs.o libblkid/src/superblocks/.libs/libblkid_la-refs.o libblkid/src/superblocks/.libs/libblkid_la-nvidia_raid.o libblkid/src/superblocks/.libs/libblkid_la-ocfs.o libblkid/src/superblocks/.libs/libblkid_la-promise_raid.o libblkid/src/superblocks/.libs/libblkid_la-reiserfs.o libblkid/src/superblocks/.libs/libblkid_la-romfs.o libblkid/src/superblocks/.libs/libblkid_la-silicon_raid.o libblkid/src/superblocks/.libs/libblkid_la-squashfs.o libblkid/src/superblocks/.libs/libblkid_la-superblocks.o libblkid/src/superblocks/.libs/libblkid_la-swap.o libblkid/src/superblocks/.libs/libblkid_la-sysv.o libblkid/src/superblocks/.libs/libblkid_la-ubifs.o libblkid/src/superblocks/.libs/libblkid_la-udf.o libblkid/src/superblocks/.libs/libblkid_la-ufs.o libblkid/src/superblocks/.libs/libblkid_la-vfat.o libblkid/src/superblocks/.libs/libblkid_la-via_raid.o libblkid/src/superblocks/.libs/libblkid_la-vmfs.o libblkid/src/superblocks/.libs/libblkid_la-vxfs.o libblkid/src/superblocks/.libs/libblkid_la-xfs.o libblkid/src/superblocks/.libs/libblkid_la-zfs.o libblkid/src/topology/.libs/libblkid_la-topology.o libblkid/src/topology/.libs/libblkid_la-dm.o libblkid/src/topology/.libs/libblkid_la-evms.o libblkid/src/topology/.libs/libblkid_la-ioctl.o libblkid/src/topology/.libs/libblkid_la-lvm.o libblkid/src/topology/.libs/libblkid_la-md.o libblkid/src/topology/.libs/libblkid_la-sysfs.o  -Wl,--whole-archive ./.libs/libcommon.a -Wl,--no-whole-archive  -Wl,-rpath -Wl,/tmp/util-linux-20161128-10735-167dxgr/util-linux-2.29/.libs -Wl,-rpath -Wl,/home/utasart/.linuxbrew/Cellar/util-linux/2.29/lib -L/home/utasart/.linuxbrew/lib ./.libs/libuuid.so  -Os -march=native -Wl,--version-script -Wl,./libblkid/src/libblkid.sym -Wl,--dynamic-linker=/home/utasart/.linuxbrew/lib/ld.so -Wl,-rpath -Wl,/home/utasart/.linuxbrew/lib   -Wl,-soname -Wl,libblkid.so.1 -o .libs/libblkid.so.1.1.0
libtool: link: (cd ".libs" && rm -f "libblkid.so.1" && ln -s "libblkid.so.1.1.0" "libblkid.so.1")
libtool: link: (cd ".libs" && rm -f "libblkid.so" && ln -s "libblkid.so.1.1.0" "libblkid.so")
libtool: link: (cd .libs/libblkid.lax/libcommon.a && ar x "/tmp/util-linux-20161128-10735-167dxgr/util-linux-2.29/./.libs/libcommon.a")
copying selected object files to avoid basename conflicts...
libtool: link: ln libblkid/src/superblocks/libblkid_la-minix.o .libs/libblkid.lax/lt1-libblkid_la-minix.o || cp libblkid/src/superblocks/libblkid_la-minix.o .libs/libblkid.lax/lt1-libblkid_la-minix.o
libtool: link: ln libblkid/src/topology/libblkid_la-lvm.o .libs/libblkid.lax/lt2-libblkid_la-lvm.o || cp libblkid/src/topology/libblkid_la-lvm.o .libs/libblkid.lax/lt2-libblkid_la-lvm.o
libtool: link: ar cru .libs/libblkid.a libblkid/src/libblkid_la-init.o libblkid/src/libblkid_la-cache.o libblkid/src/libblkid_la-config.o libblkid/src/libblkid_la-dev.o libblkid/src/libblkid_la-devname.o libblkid/src/libblkid_la-devno.o libblkid/src/libblkid_la-encode.o libblkid/src/libblkid_la-evaluate.o libblkid/src/libblkid_la-getsize.o libblkid/src/libblkid_la-llseek.o libblkid/src/libblkid_la-probe.o libblkid/src/libblkid_la-read.o libblkid/src/libblkid_la-resolve.o libblkid/src/libblkid_la-save.o libblkid/src/libblkid_la-tag.o libblkid/src/libblkid_la-verify.o libblkid/src/libblkid_la-version.o libblkid/src/partitions/libblkid_la-aix.o libblkid/src/partitions/libblkid_la-bsd.o libblkid/src/partitions/libblkid_la-dos.o libblkid/src/partitions/libblkid_la-gpt.o libblkid/src/partitions/libblkid_la-mac.o libblkid/src/partitions/libblkid_la-minix.o libblkid/src/partitions/libblkid_la-partitions.o libblkid/src/partitions/libblkid_la-sgi.o libblkid/src/partitions/libblkid_la-solaris_x86.o libblkid/src/partitions/libblkid_la-sun.o libblkid/src/partitions/libblkid_la-ultrix.o libblkid/src/partitions/libblkid_la-unixware.o libblkid/src/superblocks/libblkid_la-adaptec_raid.o libblkid/src/superblocks/libblkid_la-bcache.o libblkid/src/superblocks/libblkid_la-befs.o libblkid/src/superblocks/libblkid_la-bfs.o libblkid/src/superblocks/libblkid_la-btrfs.o libblkid/src/superblocks/libblkid_la-cramfs.o libblkid/src/superblocks/libblkid_la-ddf_raid.o libblkid/src/superblocks/libblkid_la-drbd.o libblkid/src/superblocks/libblkid_la-drbdproxy_datalog.o libblkid/src/superblocks/libblkid_la-drbdmanage.o libblkid/src/superblocks/libblkid_la-exfat.o libblkid/src/superblocks/libblkid_la-ext.o libblkid/src/superblocks/libblkid_la-f2fs.o libblkid/src/superblocks/libblkid_la-gfs.o libblkid/src/superblocks/libblkid_la-hfs.o libblkid/src/superblocks/libblkid_la-highpoint_raid.o libblkid/src/superblocks/libblkid_la-hpfs.o libblkid/src/superblocks/libblkid_la-iso9660.o libblkid/src/superblocks/libblkid_la-isw_raid.o libblkid/src/superblocks/libblkid_la-jfs.o libblkid/src/superblocks/libblkid_la-jmicron_raid.o libblkid/src/superblocks/libblkid_la-linux_raid.o libblkid/src/superblocks/libblkid_la-lsi_raid.o libblkid/src/superblocks/libblkid_la-luks.o libblkid/src/superblocks/libblkid_la-lvm.o .libs/libblkid.lax/lt1-libblkid_la-minix.o libblkid/src/superblocks/libblkid_la-netware.o libblkid/src/superblocks/libblkid_la-nilfs.o libblkid/src/superblocks/libblkid_la-ntfs.o libblkid/src/superblocks/libblkid_la-refs.o libblkid/src/superblocks/libblkid_la-nvidia_raid.o libblkid/src/superblocks/libblkid_la-ocfs.o libblkid/src/superblocks/libblkid_la-promise_raid.o libblkid/src/superblocks/libblkid_la-reiserfs.o libblkid/src/superblocks/libblkid_la-romfs.o libblkid/src/superblocks/libblkid_la-silicon_raid.o libblkid/src/superblocks/libblkid_la-squashfs.o libblkid/src/superblocks/libblkid_la-superblocks.o libblkid/src/superblocks/libblkid_la-swap.o libblkid/src/superblocks/libblkid_la-sysv.o libblkid/src/superblocks/libblkid_la-ubifs.o libblkid/src/superblocks/libblkid_la-udf.o libblkid/src/superblocks/libblkid_la-ufs.o libblkid/src/superblocks/libblkid_la-vfat.o libblkid/src/superblocks/libblkid_la-via_raid.o libblkid/src/superblocks/libblkid_la-vmfs.o libblkid/src/superblocks/libblkid_la-vxfs.o libblkid/src/superblocks/libblkid_la-xfs.o libblkid/src/superblocks/libblkid_la-zfs.o libblkid/src/topology/libblkid_la-topology.o libblkid/src/topology/libblkid_la-dm.o libblkid/src/topology/libblkid_la-evms.o libblkid/src/topology/libblkid_la-ioctl.o .libs/libblkid.lax/lt2-libblkid_la-lvm.o libblkid/src/topology/libblkid_la-md.o libblkid/src/topology/libblkid_la-sysfs.o .libs/libblkid.lax/libcommon.a/libcommon_la-blkdev.o .libs/libblkid.lax/libcommon.a/libcommon_la-canonicalize.o .libs/libblkid.lax/libcommon.a/libcommon_la-color-names.o .libs/libblkid.lax/libcommon.a/libcommon_la-cpuset.o .libs/libblkid.lax/libcommon.a/libcommon_la-crc32.o .libs/libblkid.lax/libcommon.a/libcommon_la-env.o .libs/libblkid.lax/libcommon.a/libcommon_la-exec_shell.o .libs/libblkid.lax/libcommon.a/libcommon_la-fileutils.o .libs/libblkid.lax/libcommon.a/libcommon_la-idcache.o .libs/libblkid.lax/libcommon.a/libcommon_la-ismounted.o .libs/libblkid.lax/libcommon.a/libcommon_la-linux_version.o .libs/libblkid.lax/libcommon.a/libcommon_la-loopdev.o .libs/libblkid.lax/libcommon.a/libcommon_la-mangle.o .libs/libblkid.lax/libcommon.a/libcommon_la-match.o .libs/libblkid.lax/libcommon.a/libcommon_la-mbsalign.o .libs/libblkid.lax/libcommon.a/libcommon_la-md5.o .libs/libblkid.lax/libcommon.a/libcommon_la-pager.o .libs/libblkid.lax/libcommon.a/libcommon_la-path.o .libs/libblkid.lax/libcommon.a/libcommon_la-plymouth-ctrl.o .libs/libblkid.lax/libcommon.a/libcommon_la-procutils.o .libs/libblkid.lax/libcommon.a/libcommon_la-randutils.o .libs/libblkid.lax/libcommon.a/libcommon_la-setproctitle.o .libs/libblkid.lax/libcommon.a/libcommon_la-strutils.o .libs/libblkid.lax/libcommon.a/libcommon_la-strv.o .libs/libblkid.lax/libcommon.a/libcommon_la-sysfs.o .libs/libblkid.lax/libcommon.a/libcommon_la-timeutils.o .libs/libblkid.lax/libcommon.a/libcommon_la-ttyutils.o
libtool: link: ranlib .libs/libblkid.a
libtool: link: rm -fr .libs/libblkid.lax .libs/libblkid.lax
libtool: link: ( cd ".libs" && rm -f "libblkid.la" && ln -s "../libblkid.la" "libblkid.la" )
make[2]: Leaving directory `/tmp/util-linux-20161128-10735-167dxgr/util-linux-2.29'
make[1]: *** [install-recursive] Fehler 1
make[1]: Leaving directory `/tmp/util-linux-20161128-10735-167dxgr/util-linux-2.29'
make: *** [install] Fehler 2

READ THIS: https://github.com/Linuxbrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting
```

**Comment by sjackman** [comment]
@konstin Please report the output of `brew gist-logs util-linux`
You may want to install Linuxbrew in `/home/linuxbrew/.linuxbrew` if possible which will allow to use the precompiled binary bottle rather than compiling from source.

**Comment by bw-yuhogg** [comment]
@axiac I've released a new stable build with the fix. Please retry the installation; it should update you to my new build automatically.

Thanks a bunch and my apologies 🐱

**Comment by sbicode** [comment]
I encountered a similar error.
```
sheng@sheng-VirtualBox:~$ brew install node
==> Downloading https://nodejs.org/dist/v7.0.0/node-v7.0.0.tar.xz
Already downloaded: /home/sheng/.cache/Homebrew/node-7.0.0.tar.xz
Error: private method `xz_dep' called for #<DependencyCollector:0x0000000145cc10>
Please report this bug:
  https://github.com/Linuxbrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting
/home/sheng/.linuxbrew/Library/Homebrew/dependency_collector.rb:65:in `tar_needs_xz_dependency?'
/home/sheng/.linuxbrew/Library/Homebrew/download_strategy.rb:244:in `block in stage'
/home/sheng/.linuxbrew/Library/Homebrew/utils.rb:255:in `with_system_path'
/home/sheng/.linuxbrew/Library/Homebrew/download_strategy.rb:243:in `stage'
/home/sheng/.linuxbrew/Library/Homebrew/resource.rb:95:in `block in unpack'
/home/sheng/.linuxbrew/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/home/sheng/.linuxbrew/Library/Homebrew/extend/fileutils.rb:74:in `block in run'
/home/sheng/.linuxbrew/Library/Homebrew/extend/fileutils.rb:74:in `chdir'
/home/sheng/.linuxbrew/Library/Homebrew/extend/fileutils.rb:74:in `run'
/home/sheng/.linuxbrew/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/home/sheng/.linuxbrew/Library/Homebrew/resource.rb:94:in `unpack'
/home/sheng/.linuxbrew/Library/Homebrew/resource.rb:86:in `stage'
/home/sheng/.linuxbrew/Library/Homebrew/formula.rb:1799:in `stage'
/home/sheng/.linuxbrew/Library/Homebrew/formula.rb:1075:in `brew'
/home/sheng/.linuxbrew/Library/Homebrew/build.rb:112:in `install'
/home/sheng/.linuxbrew/Library/Homebrew/build.rb:189:in `<main>'
```

**Comment by sjackman** [comment]
@sbicode Try `brew update && brew install node`

**Comment by sbicode** [comment]
```
sheng@sheng-VirtualBox:~$ brew update && brew install node
Already up-to-date.
==> Downloading https://nodejs.org/dist/v7.0.0/node-v7.0.0.tar.xz
Already downloaded: /home/sheng/.cache/Homebrew/node-7.0.0.tar.xz
Error: private method `xz_dep' called for #<DependencyCollector:0x00000002945f00>
Please report this bug:
  https://github.com/Linuxbrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting
/home/sheng/.linuxbrew/Library/Homebrew/dependency_collector.rb:65:in `tar_needs_xz_dependency?'
/home/sheng/.linuxbrew/Library/Homebrew/download_strategy.rb:244:in `block in stage'
/home/sheng/.linuxbrew/Library/Homebrew/utils.rb:255:in `with_system_path'
/home/sheng/.linuxbrew/Library/Homebrew/download_strategy.rb:243:in `stage'
/home/sheng/.linuxbrew/Library/Homebrew/resource.rb:95:in `block in unpack'
/home/sheng/.linuxbrew/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/home/sheng/.linuxbrew/Library/Homebrew/extend/fileutils.rb:74:in `block in run'
/home/sheng/.linuxbrew/Library/Homebrew/extend/fileutils.rb:74:in `chdir'
/home/sheng/.linuxbrew/Library/Homebrew/extend/fileutils.rb:74:in `run'
/home/sheng/.linuxbrew/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/home/sheng/.linuxbrew/Library/Homebrew/resource.rb:94:in `unpack'
/home/sheng/.linuxbrew/Library/Homebrew/resource.rb:86:in `stage'
/home/sheng/.linuxbrew/Library/Homebrew/formula.rb:1799:in `stage'
/home/sheng/.linuxbrew/Library/Homebrew/formula.rb:1075:in `brew'
/home/sheng/.linuxbrew/Library/Homebrew/build.rb:112:in `install'
/home/sheng/.linuxbrew/Library/Homebrew/build.rb:189:in `<main>'
```

**Comment by sbicode** [comment]
thank you, brew was up-to-date but still unable to install node.

**Comment by sjackman** [comment]
Please report the output of `brew --version`

**Comment by sbicode** [comment]
```
sheng@sheng-VirtualBox:~$ brew --version
Homebrew 1.1.0
Homebrew/homebrew-core (git revision ffbb7; last commit 2016-11-27)
```

**Comment by sjackman** [comment]
This bug is resolved in 1.1.0.1. I'm not sure why `brew update` isn't upgrading to that version for you. Try
```sh
cd `brew --repo`
git fetch --tags
brew --version
brew update
brew --version
git checkout -B master 1.1.0.1
brew --version
```

**Comment by konstin** [comment]
@sjackman:

```
$ brew gist-logs util-linux
```
https://gist.github.com/4092c423bf502a1f09eb58dcc2f0bbea

Installing in `/home/linuxbrew/.linuxbrew` ist not possible as I don't have root access.

**Comment by axiac** [comment]
The update doesn't work:

    $ brew update
    Already up-to-date.
    $ brew update --force
    Already up-to-date.
    $ brew --version
    Homebrew 1.1.0
    Homebrew/homebrew-core (git revision ffbb7; last commit 2016-11-27)

I removed `~/.linuxbrew`, installed a fresh copy, ran the above commands again and got the same results.

**Comment by sjackman** [comment]
@axiac I'm not sure why `brew update` isn't upgrading to 1.1.0.1 for you. Try

```
cd `brew --repo`
git fetch --tags
brew --version
brew update
brew --version
git checkout -B master 1.1.0.1
brew --version
```

**Comment by sjackman** [comment]
@konstin wrote…
> Installing in `/home/linuxbrew/.linuxbrew` is not possible as I don't have root access.

You could open a ticket asking your systems/IS/IT group to create a `linuxbrew` role account for you.

**Comment by sjackman** [comment]
@konstin `/home/utasart/.linuxbrew/bin/ld: cannot find -lpam`
https://gist.github.com/anonymous/4092c423bf502a1f09eb58dcc2f0bbea#file-02-make-L839
The issue is open at Linuxbrew/homebrew-core#1018.
There's a PR open to add a `linux-pam` formula to Linuxbrew at PR https://github.com/Linuxbrew/homebrew-core/pull/1186

**Comment by axiac** [comment]
@sjackman It's not "it doesn't work for you". It doesn't work at all, not only for me. Read my previous comment again, please. I removed the `~/.linuxbrew` directory and installed Linuxbrew from scratch. What I got was version 1.1.0, not 1.1.0.1.

`cd ~/.linuxbrew; git branch -v` reveals that the current branch in `~/.linuxbrew` is `stable` (I didn't run anything else inside the repo):

    $ git branch -v
      master 83d6f8c dependency_collector: Make ant_dep and xz_dep public (#183)
    * stable 17a0c41 Merge tag Homebrew/1.1.0 into Linuxbrew/master

After `git checkout master`, `brew --version` reports `1.1.0.1` and `gettext` installs without errors.

I hope this helps you finding the cause of the issue.

**Comment by sjackman** [comment]
Ah, that's why it works for me and not for you. My branch was already `master`. We'll have to look into why the `stable` branch doesn't automatically update to `1.1.0.1`.
@maxim-belkin is working on merging and pushing version `1.1.1` which will resolve this issue.
For other people following this thread, the workaround is
```sh
cd `brew --repo` && git checkout -B stable 1.1.0.1
```

**Comment by bw-yuhogg** [comment]
The problem appears to be here: https://github.com/Linuxbrew/brew/blob/master/Library/Homebrew/cmd/update.sh#L220-L222

```bash
UPSTREAM_TAG="$(git tag --list |
                    sort --field-separator=. --key=1,1nr -k 2,2nr -k 3,3nr |
                    grep --max-count=1 '^[0-9]*\.[0-9]*\.[0-9]*$')"
```

It's the last `grep` that causes the issue; the tag is found but 1.1.0 is selected instead of 1.1.0.1 since it assumes a 3-digit version string.

Suffice it to say that this at least proves that releasing 1.1.1 should resolve this.

**Comment by sjackman** [comment]
We may want to change this regex in case future Linuxbrew hotfix patches are needed.

**Comment by bw-yuhogg** [comment]
@axiac, @konstin, @sbicode:  I've merged 1.1.1.

Please retry the installation that was failing for you previously. You should be updated to 1.1.1 automatically when you do so, but if that doesn't work then please do a `brew update` and then try the installation again.

Thank you all for your patience as I worked through this issue.

I'm going to be online for a few more hours and I will respond to any issues with this you report as quickly as I can.

**Comment by sjackman** [comment]
This issue should be resolved by Linuxbrew 1.1.1.

**Comment by axiac** [comment]
@rwhogg @sjackman It works correctly now. Thank you both for your quick responses and solution.

**Comment by sjackman** [comment]
Happy to help.
